# Generated by Django 4.1.6 on 2023-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('bookId', models.CharField(default='', max_length=8)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
