# Generated by Django 4.1.6 on 2023-03-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
