# Generated by Django 4.1.6 on 2023-03-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
        ('api', '0003_review'),
    ]

    operations = [
    ]
