# Generated by Django 4.1.6 on 2023-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageURL',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
