# Generated by Django 4.1.6 on 2023-03-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
    ]
